name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build frontend Docker image
        run: docker build -t my-frontend ./frontend

      - name: Build backend Docker image
        run: docker build -t my-backend ./backend

      - name: Deploy frontend container
        run: |
          docker stop my-frontend || true
          docker rm my-frontend || true
          docker run -d -p 5000:5000 --name my-frontend my-frontend

      - name: Deploy backend container
        run: |
          docker stop my-backend || true
          docker rm my-backend || true
          docker run -d -p 3000:3000 --name my-backend my-backend
